accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signin/', views.SignInView.as_view(), name='signin'),
	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('', views.SignUpView.as_view(), name='signup'),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'
urlpatterns = [

	path('', views.RoomHomeView.as_view(), name='home'),
	path('<int:pk>/', views.JoinRoomView.as_view(), name='join-room'),

	# ajax views
	path('<int:pk>/update-room-description/', views.UpdateRoomDescription.as_view(), name='update-room-description'),
	path('search/', views.RoomHomeView.as_view(), name='room-search'), # add name='room-search'
]

skrib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('rooms/', include('rooms.urls', namespace='rooms')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from rooms.models import Room

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='media/', default='media/None/no-img.jpg')
    current_room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True)
    guest_user = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.core.exceptions import ValidationError # [Fixing Merge Conflicts] added this


class SignUpForm(forms.ModelForm):
	username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder' : 'Username'}))
	password_submit = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder' : 'Password'}), min_length=8)
	password_confirm = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder' : 'Repeat Password'}), min_length=8)
	email = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder' : 'Email'}))

	class Meta:
		model = User
		fields = ["username", "password_submit", "password_confirm", "email"] # these are the fields in the form, may or may not use

	def clean_password_confirm(self):
		password_confirm = self.cleaned_data.get('password_confirm')
		password_submit = self.cleaned_data.get('password_submit')
		if password_confirm != password_submit:
			raise forms.ValidationError('Password does not match.')
		return password_confirm

	def clean_email(self):
		try:
			email = self.cleaned_data.get('email') # [Fixing Merge Conflicts] from cleaed_data
			validate_email(email)
			return email
		except ValidationError: # [Fixing Merge Conflicts] from validate_email.ValidationError
			raise forms.ValidationError('Use a Proper Email')

class SignInForm(forms.ModelForm):
	username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder' : 'Username'}))
	password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder' : 'Password'}))

	class Meta:
		model = User
		fields = ["username", "password"] # these are the fields in the form

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import SignUpForm, SignInForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
class SignUpView(View):
    form_class = SignUpForm
    template_name = 'accounts/signup.html'

    def get(self, request):
        user = self.request.user
        
        if user.is_authenticated and not user.profile.guest_user:
            return redirect('rooms:home')
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = self.form_class(request.POST)
        if (form.is_valid()):
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password_submit = form.cleaned_data['password_submit']
            password_confirm = form.cleaned_data['password_confirm']
            user.set_password(password_submit)
            user.save()
            user = authenticate(username=username, password=password_submit)
            if user is not None:
                login(request, user)
                return redirect('rooms:home')
        return render(request, self.template_name, {'form' : form})

class SignInView(View):
    form_class = SignInForm
    template_name = 'accounts/signin.html'

    def get(self, request):
        user = self.request.user

        if user.is_authenticated and not user.profile.guest_user:
            return redirect('rooms:home')
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = self.form_class(request.POST)

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('rooms:home')

        return render(request, self.template_name, {'form' : form})

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('accounts:signup')

accounts/templates/accounts/form_template.html
{% for field in form %}
	<div class="regform__group">
		<div class="regform__field">
			<div class="regform__text">{{ field }}</div>
			<div class="text-danger small color-error">{{ field.errors }}</div>
		</div>
	</div>
{% endfor %}

accounts/templates/accounts/signin.html
{% extends "assets/registration.leftart.html" %}

{% block regform %}

<div class="panel-body">
    <h3 class='regformlabel'>Log in to your account</h3>
    {% if error_message %}
        <p class='color-error'><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <span class="col-sm-offset-2 col-sm-10">
                    <span class="col-sm-10 regform__text">{{ field }}</span>
                    {% if field.errors %}
                        <span class="text-danger small">Invalid username or password.</span>
                    {% endif %}
                </span>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 flexboxcontainer centerjustify">
                <button type="Submit" class="btn-success skrib-button cta">Log In</button>
            </div>
        </div>
    </form>
    <div class='helpmessage__container'>
        <p> You don't have an account? </p>
        <span> <a href='{% url 'accounts:signup' %}'> Create a new one </a> </span>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "assets/landing.html" %}

{% block titleblock %}
    Sign up to Skrib! A real-time shared white whiteboard
{% endblock titleblock %}

{% block regform %}

<div class="panel-body">
    <h3 class='ctapanel__header '>Sign up and find out how Skrib can help you share your ideas!</h3>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group">
            <span class="col-sm-offset-2 col-sm-10">
              <span class="col-sm-10 regform__text">{{ field }}</span>
              <span class="text-danger small">{{ field.errors.as_text }}</span>
            </span>
          </div>
        {% endfor %}
        <div class="form-group">
          {% csrf_token %} <!-- added this -->
            <div class="col-sm-offset-2 col-sm-10 flexboxcontainer centerjustify">
                <button type="Submit" class="btn btn-success cta submitbtn">Sign Up</button>
            </div>
        </div>
    </form>
    <div class='helpmessage__container'>
      <p>Already have an account? </p>
      <span><a href="{% url 'accounts:signin' %}">Log in</a></span>
    </div>
</div>

{% endblock %}