accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signin/', views.SignInView.as_view(), name='signin'),
	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('', views.SignUpView.as_view(), name='signup'),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'
urlpatterns = [

	path('', views.RoomHomeView.as_view(), name='home'),
	path('<int:pk>/', views.JoinRoomView.as_view(), name='join-room'),

	# ajax views
	path('<int:pk>/update-room-description/', views.UpdateRoomDescription.as_view(), name='update-room-description'),
	path('search/', views.RoomHomeView.as_view(), name='room-search'), # add name='room-search'
]

skrib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('rooms/', include('rooms.urls', namespace='rooms')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rooms/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from datetime import datetime
from channels import Group
from comments.settings import MSG_TYPE_MESSAGE
from django.urls import reverse
from django.db import transaction
from django.db.models import F

from django.contrib.auth.models import User
import tagulous.models

@python_2_unicode_compatible
class Room(models.Model):
    ROOM_CATEGORIES = [
        ('Educational', 'Educational'),
        ('Science', 'Science'),
        ('Music','Music'),
        ('Food', 'Food'),
        ('Socializing', 'Socializing'),
        ('Others', 'Others')
    ]

    presentor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(default="No Room Description Available")
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    is_private = models.BooleanField(default=False)
    room_categories = models.CharField(choices=ROOM_CATEGORIES, max_length=50, default='Educational')
    room_streaming = models.CharField(max_length=300)
    pdf_file = models.TextField(null=True, blank=True)
    pdf_file_name = models.TextField(null=True, blank=True)

    def is_presentor(self, user):
        return self.presentor.username == user

    def get_room_category(self):
        return self.room_categories

    def is_room_private(self):
        return self.is_private == True

    def get_absolute_url(self):
        return reverse('rooms:join-room', kwargs={ 'pk': self.pk })

    server_cursor_comments = models.BigIntegerField(default=0)
    comments = models.TextField(default="", blank=True)
    server_cursor_scribbles = models.BigIntegerField(default=0)
    scribbles = models.TextField(default="", blank=True)

    def __str__(self):
        return self.title

    def websocket_group(self, source):
        return Group("room-%s-%s" % (self.id, source))


    @classmethod
    def send_message(cls, id, message, user, source, msg_type=MSG_TYPE_MESSAGE):
        with transaction.atomic():
            room = (
                cls.objects
                .select_for_update(nowait=False)
                .get(id=id)
            )
            final_msg = {"room": str(id), "message": message, "username": user.username, "msg_type": msg_type, "server_cursor": room.server_cursor_scribbles}
            if source == 'comment':
                # room.comments = str(room.comments) + str(room.server_cursor_comments) + " " +  json.dumps(final_msg) + "\n"
                # room.server_cursor_comments += 1
                pass
            elif source == 'scribble':
                save_msg = final_msg.copy()
                # save_msg["message"] = [message for message in save_msg["message"]
                #                         if message["event"] not in ["putPoint", "prev_page_PDF", "next_page_PDF",
                #                             "checkboxPDF", "checkboxPDFCanvas", "checkboxCanvas"]]
                save_msg_list = []
                for message in save_msg["message"]:
                    if message["event"] not in ["putPoint"]:
                        save_msg_list.append(message)
                    if message["event"] == "openPDF":
                        room.pdf_file = message["file"]
                        room.pdf_file_name = message["filename"]
                save_msg["message"] = save_msg_list
                room.scribbles = str(room.scribbles) + str(room.server_cursor_scribbles) + " " + json.dumps(save_msg) + "\n"
                room.server_cursor_scribbles += 1

            room.save()

            room.websocket_group(source).send(
                {"text": json.dumps(final_msg)}
            )
        return room

    def send_message_cursor(self, message, user, source):
        final_msg = {"room": str(self.id), "message": message, "username": user.username}
        self.websocket_group(source).send(
            {"text": json.dumps(final_msg)}
        )

    def send_comment(self, message, user, msg_type=MSG_TYPE_MESSAGE):
        with transaction.atomic():
            final_msg = {"room": self.id, "message": message, "username": user.username, "msg_type": msg_type}

            comment = Comment(comment_source_room=self, comment_room_cursor=self.server_cursor_comments, commenter=user, comment_text=message)
            comment.save()

            self.server_cursor_comments = F('server_cursor_comments') + 1
            self.save()

            self.websocket_group('comment').send(
                {"text": json.dumps(final_msg)}
            )

    def get_comments(self, client_cursor):
        comments = Comment.objects.filter(comment_source_room=self, comment_room_cursor__gte=client_cursor).order_by('comment_room_cursor')
        comments_list = [{"username":comment.commenter.username, "message":comment.comment_text, "msg_type":0} for comment in comments]
        return comments_list

    def get_scribbles(self, client_cursor):
        scribbles_list = str(self.scribbles).split('\n')[client_cursor:-1]
        scribbles_list = [(scribble[scribble.find(' ')+1:]) for scribble in scribbles_list]
        return scribbles_list

class Comment(models.Model):
    comment_source_room = models.ForeignKey(Room, on_delete=models.CASCADE)
    comment_room_cursor = models.IntegerField(default=0)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    comment_created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment_text[:50]

rooms/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import validate_email
from .models import Room

class RoomForm(forms.ModelForm):
    room_categories = forms.CharField(widget=forms.Select(choices=Room.ROOM_CATEGORIES))
    is_private = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={
            'class' : 'switch-input',
            'name' : 'is_private'
        }))

    class Meta:
        model = Room
        fields = ['title', 'room_categories', 'is_private']

    def __init__(self, *args, **kwargs):
        super(RoomForm, self).__init__(*args, **kwargs)
        self.fields['is_private'].required = False

class MultipleEmailField(forms.Field):
    def to_python(self, value):
        if not value:
            return []
        return value.split(', ')

    def validate(self, value):
        super().validate(value)
        for email in value:
            validate_email(email)

class PrivateRoomAdmin(forms.ModelForm):
    room_categories = forms.CharField(widget=forms.Select(choices=Room.ROOM_CATEGORIES))
    users = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        choices=[(user.username, user.username) for user in User.objects.all()]
    )
    guest_users = MultipleEmailField()

    def __init__(self, *args, **kwargs):
        super(PrivateRoomAdmin, self).__init__(*args, **kwargs)
        self.fields['users'].required = False
        self.fields['guest_users'].required = False

    class Meta:
        model = Room
        fields = ['title', 'description', 'room_categories', 'is_private']

rooms/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from .models import Room
from .forms import RoomForm
from .streaming import CreatingWebStreaming
from accounts.models import Profile
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.contrib.auth import login
import json

def sending_invites_to_other_users(presenter, room_key, room_title, invited_users, request):
    presenter = User.objects.get(username=presenter)
    mail_subject = 'This is an invite to ' + room_title + ' for you to join in'
    mail_message = 'Please paste the link or enter ' + request.get_host() + reverse('rooms:join-room', args=(room_key,))
    send_mail(mail_subject, mail_message, presenter.email, invited_users, fail_silently=False,)

class RoomHomeView(generic.View):
    template_name = "rooms/classroom-lists.html"
    login_url = 'accounts:signin'
    redirect_field_name = 'redirect_to'
    form_class = RoomForm
    model = Room
    room_category_list = [room_category[1] for room_category in Room.ROOM_CATEGORIES]
    users = json.dumps([user[0] for user in User.objects.values_list('email')])

    def post(self, request):
        form = self.form_class(request.POST)
        if (form.is_valid()):
            room = form.save(commit=False)
            room_session = CreatingWebStreaming()
            session = room_session.create_session()
            room.room_streaming = session.session_id
            room_email_skrib_and_guest_users = request.POST.getlist('tags')
            room.presentor = User.objects.get(pk=self.request.user.id)
            room.save()
            if (room_email_skrib_and_guest_users):
                sending_invites_to_other_users(presenter=room.presentor, room_key=room.id, room_title=room.title, invited_users=room_email_skrib_and_guest_users, request=request)
            return HttpResponseRedirect(reverse('rooms:join-room', args=(room.id,)))

    def get(self, request):
        user = self.request.user
        rooms = Room.objects.filter(date_created__lte=timezone.now(), is_private=False).order_by('-date_created')
        newCategoryList = []
        for room in rooms:
            if room.room_categories not in newCategoryList:
                newCategoryList.append(room.room_categories)
        if user.is_authenticated:            
            if request.is_ajax():
                room_name = request.GET.get('searched_room_name')
                searched_classrooms = Room.objects.filter(title__contains=room_name)
                context = []
                for room in searched_classrooms:
                    data = {
                        'presentor' : room.presentor.username,
                        'title' : room.title,
                        'id' : room.id,
                        'description' : room.description
                    }
                    context.append(data)
                return JsonResponse({'searched_classrooms' : context})
            else:
                form = self.form_class(None)
                return render(request, self.template_name, {
                        'form' : form,
                        'created_classrooms' : rooms,
                        'room_category_list' : newCategoryList,
                        'users_list' : self.users
                    })
        else:
            return redirect('accounts:signup')

class JoinRoomView(generic.DetailView):
    model = Room
    template_name = "rooms/classroom-detail.html"

    def get(self, request, pk):
        self.object = self.get_object()
        if not request.user.is_authenticated:
            user = User(username='guest{}'.format(User.objects.count()))
            user.save()
            user.profile.guest_user = True
            login(request, user)
        return render(request, self.template_name, self.get_context_data())

    def get_context_data(self, **kwargs):
        room = Room.objects.get(pk=self.kwargs.get('pk'))
        room_session = CreatingWebStreaming()
        if not room.room_streaming and self.request.user.username != room.presentor:
            session = room_session.create_session()
            room.room_streaming = session.session_id
            room.save()
        token = room_session.generate_token(room.room_streaming)
        context = super().get_context_data(**kwargs)
        context['api_key'] = room_session.api_key
        context['sessionId'] = room.room_streaming
        context['token'] = token
        return context

class UpdateRoomDescription(generic.View):
    def post(self, request, *args, **kwargs):
        room_description = request.POST.get('room_description')
        room_id = request.POST.get('room_id')
        room = get_object_or_404(Room, id=room_id)
        room.description = room_description
        room.save()
        context = {
            'roomDescription' : room_description,
        }
        return JsonResponse(context)

rooms/templates/rooms/classroom-lists.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- css files -->
    <link rel="stylesheet" type="text/css" href='{% static "global/styles/positioning2.css"%}'>
    <link rel="stylesheet" type="text/css" href='{% static "global/styles/colors2.css"%}'>
    <link rel="stylesheet" type="text/css" href='{% static "global/styles/fonts2.css"%}'>
    <link rel="stylesheet" type="text/css" href='{% static "global/styles/elementmodifiers2.css"%}'>
    <link rel="stylesheet" type="text/css" href='{% static "global/styles/responsive2.css"%}'>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href='{% static "rooms/css/jquery.tagit.css" %}'>
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"
    integrity="sha384-OHBBOqpYHNsIqQy8hL1U+8OXf9hH6QRxi0+EODezv82DfnZoV7qoHAZDwMwEJvSw"
    crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- javascript files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src='{% static "rooms/js/tag-it.js" %}'></script>
    <script type="text/javascript" src='{% static "global/script/home.js" %}' defer></script>

    <link rel="shortcut icon" href='{% static "global/img/logo-draft2.ico" %}' />

    <title>Skrib</title>
</head>
<body>
    <div class="masthead color-white">
        <div id='masthead__container' class='flexboxcontainer spacebetween color-white'>
            <div id='branding__container' class='flexboxitem'>
                <div class='flexboxcontainer flexstart'>
                  <img id='logo' class='logo' src='{% static "global/img/masthead.logo.svg" %}' width='50' alt='skrib-logo'/>
                  <h1 id='logotype' class='logotype color-accent questrial-font'> skrib </h1>
                </div>
            </div>
            <div id='lndpg_nav' class='flexboxitem'>
              <div class='flexboxcontainer spaceevenly'>
                    {% if not user.profile.guest_user %}
                    <a id='streambtn' class='navbtn uppercase color-main gradient-btn' href='#'>Stream</a>
                    {% else %}
                    <a id='streambtn' class='navbtn uppercase color-main gradient-btn' style="display:none;" href='#'>Stream</a>
                    {% endif %}
                    <form action="{% url 'rooms:room-search' %}" method="get">
                        <input id='search-room' class="js-search material-icons" type="search" placeholder="Search">
                    </form>
                    <a id='profbtn' href='#' class='account'>
                        <span class="profile-pic"></span>
                    </a>
              </div>
            </div>
        </div>
    </div>

    <div id="myModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-h2-header">
                    Room Details
                    <span class="close"><i class="material-icons">close</i></span>
                </h2>
            </div>
            <div class="modal-body">
                <form class="pure-form-aligned pure-form" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <div class="pure-control-group">
                            <div class="margin-form">
                                <label for="room-name">Room Name</label>
                                {{ form.title }}
                            </div>
                            <div class="margin-form">
                                <label for="room-name">Categories</label>
                                {{ form.room_categories }}
                            </div>

                            <div class="margin-form">
                                <label for="private-room">Private Room</label>
                                <label class="switch">
                                    {{ form.is_private }}
                                    <span class="switch-label" data-on="Yes" data-off="No"></span>
                                    <span class="switch-handle"></span>
                                </label>
                            </div>
                            <div class="invite-cls">
                            <span class="invite-people">Invite people using their email address</span>
                                <ul id='invite_guest_or_skrib_users'></ul>
                            </div>
                            <div class="pure-controls">
                                <button id="submit-btn" type="submit" class="pure-button pure-button-primary gradient-btn uppercase">Create Room</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

     <div id="prof-modal" class="profile-modal">
        <div class="profile-modal-content">
            <div class="profile-picture">
                <span class="profile-pic-deets"></span>
            </div>
            <div class="account-details">
              <h2 id='name'>{{ user }}</h1>
              {% if not user.profile.guest_user %}
                <h5 id='email'>{{ user.email }}</h4>
                <a href="{% url 'accounts:logout' %}">Log Out</a>
              {% else %}
                <a href="{% url 'accounts:signup' %}">Signup</a>
              {% endif %}
            </div>
        </div>
    </div>

    <!-- Search results -->
    <div class='search-results' style="display: none;">
        <div id='searched-classroom-results'>
        </div>
    </div>

    <!-- Main Body -->
    <div class='main-body'>
        {% if created_classrooms %}
            {% if room_category_list %}
                {% for room_category in room_category_list %}
                    <div class="main header"><h2>{{ room_category }}</h2></div>
                        <div class='main first-div'>
                            {% for classroom in created_classrooms %}
                                {% if classroom.get_room_category == room_category %}
                                    <div class="card">
                                        <a href="{% url 'rooms:join-room' classroom.id %}" class="navbtn color-main">
                                            <img src='{% static "global/img/logo-draft2-sqr.svg" %}' class="img-container">
                                            <div class="card-desc">
                                                <p class="text">
                                                    {{ classroom.description }}
                                                </p>
                                            </div>
                                            <div class="container">
                                                <span><h3 class="container-text">{{ classroom.title }}</h3></span>
                                                <span class="profile-pic-small"></span><p class="container-text">{{ classroom.presentor }}</p>
                                            </div>
                                        </a>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <!--Phantom cards-->
                            <div style="justify-content: space-between;"></div>
                            <div style="justify-content: space-between;"></div>
                            <div style="justify-content: space-between;"></div>
                        </div>
                    <div class='main horizontal-divider'></div>
                {% endfor %}
            {% endif %}

        {% else %}
            <h1>No public classrooms available.</h1>
            <p>Create one by clicking the STREAM button!</p>
        {% endif %}
    </div>

    <script>
        var users_list = JSON.parse("{{users_list|escapejs}}");
    </script>
    <script type="text/javascript" src='{% static "rooms/js/invite-users.js" %}'></script>
</body>
</html>